export const PortfolioDB = [
  {
    name: "Nauka",
    array: [
      {
        title: "CSS 1",
        message:
          "Pierwsza zabawa z flexboxem. Ułożenie danych divow z ustaloną konwencją.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 2",
        message: "Utworzenie responsywnego layoutu za pomocą flexboxa.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 3",
        message: "Stworzone za pośrednictwem flexboxa responsywne menu.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 4",
        message:
          "Kalkulator bez funkcjonalności podstawowych, lecz zrobiony we flexboxie.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 5",
        message:
          "Trudne zadanie z flexboxa. Ułożenie przycisków w równej linii.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 6",
        message:
          "Ćwiczenie polegające na ułożenie obrazu z kilka obrazków za pomocą 'position: absolute'.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 7",
        message: "Pozycjonowanie szachownicy.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 8",
        message: "Budujemy własny dom!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 9",
        message: "Zmiana kolorów za pomocą animacji.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 10",
        message:
          "Zadanie polegające na uruchomieniu animacji za pomocą przycisku.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 11",
        message: "Po najechaniu na zegar, zaczyna się poruszać.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 12",
        message:
          "Przykład przycisku. Można wykonać za pomocą span'a lub za pomocą after, before.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 13",
        message: "Przykład przycisku.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 14",
        message: "Przykład przycisków, które wchodzą w interakcję z tekstem.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 15",
        message: "Przykład przycisku.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 16",
        message:
          'Przykładowy prosty baner wykonany poprzez "@keyframes" (animację).',
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 17",
        message: "Pierwszy przykład animacji hamburgra!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 18",
        message: "Drugi przykład animacji hamburgra!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 19",
        message: "Trzeci przykład animacji hamburgra!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 20",
        message: "Czwarty przykład animacji hamburgra!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 21",
        message: "Piąty przykład animacji hamburgra!",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 22",
        message: "Dodawanie kwadratów za pomocą JQuery.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 23",
        message: 'Prosty projekt "Modal Popup".',
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CSS 24",
        message: "Skrolowanie menu za pośrednictwem przycisków.",
        html: true,
        css: true,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },
      {
        title: "JavaScript 1",
        message:
          "Dodawanie kwadratu za pomocą przycisku oraz dodanie klasy active.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 2",
        message: "Ćwiczenie polegające na interakcję elementu ze scrollem.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 3",
        message: "Naciśnij na dowolny piksel.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 4",
        message: "Przeciągnij kwadrat.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 5",
        message:
          "Klawiszem strzałka w dół przyciemnij a strzałką w górę rozjaśnij.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 6",
        message: "Tajny kod (hasło: user).",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 7",
        message:
          "Niech komputer za Ciebie zdecyduje co masz zrobić w danej chwili. Dodaj swoje możliwości oraz zdaj się na komputer!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 8",
        message: "Generator kodów!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 9",
        message:
          "Jeżeli jesteś mocny, to postaraj się wygrać z komputerem w papier, nożyce, kamień!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 10",
        message: "Efekt pisania na maszynie!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 11",
        message: "Aktualna godzina!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 12",
        message: "Odliczanie do konkretnej daty.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 13",
        message: "Zmierz czas moim stoperem.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 14",
        message: "Prosta toDo lista.",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "JavaScript 15",
        message:
          "Sprawdź czy wygrasz! Jednoręki bandyta stoi przed tobą i chce żebyś zakręcił! Uważaj, gdyż gra jest mocno uzależniająca!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },
      {
        title: "React 1",
        message:
          "Dodaj cyfrę! Komponent funkcyjny, dodawanie cyfry za pomocą przycisku",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 2",
        message: "Obsługa inputu. Wpisz dowolną wartość",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 3",
        message: "Pokaż, ukryj wiadomość",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 4",
        message: "Zlicz ilość kliknięć oraz wynik",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 5",
        message: "Sprawdź czy możesz zakupić bilet na horror roku!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 6",
        message: "Kup produkt, tylko 7 na stanie magazynowym",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 7",
        message: "Złóż zamówienie!",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 8",
        message:
          "Sprawdź cennik paliwa, pomarańczy oraz prądu w: euro, złotówkach, dolarach i funtach",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 9",
        message: "Losuj wróżbę oraz dodaj ją sam",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 10",
        message: "Dodaj gości do swojej listy",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 11",
        message: "Pierwszy projekt napisany przy pomocy create react app",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 12",
        message: "Odśwież wynik co konkretną ilość sekund",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 13",
        message: "Pobieranie danych z danej strony (API)",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 14",
        message: "Walidacja formularza, zabezpieczenia",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 15",
        message: "Prosty projekt todo listy",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 16",
        message: "Wstępny projekt sklepu, React Router 6, useEffect",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 17",
        message: "Drugi projekt todo listy",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 18",
        message: "Dowiedz się czegoś nowego o emoji",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "React 19",
        message: "Ostylowany login login: user, hasło: user",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },
      {
        title: "React 20",
        message: "Zobacz aktualny czas",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },
      {
        title: "React 21",
        message:
          "Wyświetlanie kontaktów za pomocą przesyłu propsów oraz tablicy",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: true,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },
    ],
  },
  {
    name: "Projekty",
    array: [
      {
        title: "Lista rozwijana",
        message:
          'Pierwszy projekt, który okazał się głębokim oceanem. Prócz responsywnej strony chciałem uzyskać efekt "plusów" w navbarze aby rozszerzyć listę.',
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Zegar",
        message:
          "Próba odtworzenia prawdziwego zegara zakończona powodzeniem! :)",
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "ProGamers",
        message:
          'Strona stworzona za pomocą bootstrapa oraz przy pomocy kursu "https://www.udemy.com/course/od-zera-do-front-end-developera-cz2/" autor: Mateusz Maj!',
        html: true,
        css: true,
        scss: false,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: true,
      },

      {
        title: "Library+",
        message:
          "Zapoczątkowanie mojej własnej biblioteki, która jest w trakcie realizacji (własny slider z animacją i responsywnością)!",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "CVWEB",
        message: "Strona prezentacyjna!",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Poprzednie CV",
        message:
          "Moje poprzednie CV. Z uwagi na dużą ilość mb, niektóre funkcje są niedostępne!",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "SVG social animations",
        message: "Przykłady animacji social mediów.",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Computers",
        message:
          "Animacja typu 'morph' za pomocą biblioteki anime-master oraz Adobe After Effects oraz zabawa animacją w CSS.",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "ICE-GOOD",
        message: "Strona informacyjna wymyślonej przeze mnie firmy lodów.",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: true,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Mountains are awesome!",
        message: "Strona informacyjna o podróżach w góry!",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: true,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Gra",
        message: "Ułóż od 1 do 15 w odpowiedniej kolejności!",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: true,
        pencil: false,
        bootstrap: false,
      },
    ],
  },
  {
    name: "Klienci",
    array: [
      {
        title: "Title 1",
        message: "Klient 1",
        html: true,
        css: true,
        scss: true,
        js: true,
        react: true,
        node: true,
        mysql: true,
        illustrator: true,
        photoshop: true,
        pencil: false,
        bootstrap: false,
      },
    ],
  },
  {
    name: "Rysunki",
    array: [
      {
        title: "Dragon Ball - Goku SSJ Blue",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825818/cv/drawings/gokublue_jfo0ay.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Kościół Mariacki",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825821/cv/drawings/kosciolmariacki_gb2fgu.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Lew",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825821/cv/drawings/lion_bn8jx0.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "1 World Trade Center",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825818/cv/drawings/1wtc_tldoe2.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Fiat 126p",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825820/cv/drawings/fiat126p_vfndgq.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Wieża Eiffla",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825823/cv/drawings/wiezaeiffla_s5rkyk.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Domek zimą",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825820/cv/drawings/houseinmountains_qfjyzk.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Crysis 2",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825821/cv/drawings/prorok_vo7d2i.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "F-35",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825818/cv/drawings/f35_gorbjf.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Young Goku",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825823/cv/drawings/young-goku_v9po6v.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Toyota Corolla",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673825821/cv/drawings/toyotacorolla_mvffma.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Logo netifashionlook - koncepcja 1",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673645230/cv/drawings/netifashion_xh6loa.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Kot",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673488166/cv/drawings/lool_Obszar_roboczy_1_td1kat.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Krajobraz gór",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673737595/cv/drawings/mountain_epqdvs.png",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Informacja o wyprzedaży",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673737920/cv/drawings/black-week_dgijho.png",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: true,
        pencil: false,
        bootstrap: false,
      },

      {
        title: "Logo netifashionlook - koncepcja 2",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673851875/cv/drawings/logo2_q1ptma.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Goku MUI",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673851941/cv/drawings/goku_rdefja.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: true,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },

      {
        title: "Goku 4 forms and Shen Long",
        url: "https://res.cloudinary.com/dgubzvsvn/image/upload/v1673996688/cv/drawings/4goku_cq3dhq.jpg",
        html: false,
        css: false,
        scss: false,
        js: false,
        react: false,
        node: false,
        mysql: false,
        illustrator: false,
        photoshop: false,
        pencil: true,
        bootstrap: false,
      },
    ],
  },
];
